### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by kotajacob**
This is a really large rewrite of many of the functions to not only have better code style, but also allow for easier implementation of new features and support for more systems.

- Loads config.json with list of steam UI elements to be colored in colors.styles with which wal colors.
- More clear goal for each function, cleaned up main significantly, removed various useless functions.
- More clear comments
- Variable names are more consistent.

There's still a lot of work to be done until this is ready for release. See #46 for a list of things that need worked on.

### CODE REVIEW

**Comment by dylanaraps** [comment]
(*Not sure where to write this.*)

Windows support for `pywal` has been merged to master and a new release has been made. Windows users just need to install Python (`3.5+`) and then run `pip install pywal` to install it.
 
The user then needs to install `imagemagick` which has binary releases install-able here: https://www.imagemagick.org/script/download.php (*Scroll down to find "Windows Binary Releases"*)

You could also make `wal_steam` a `pip` package so that you can easily install both programs with `pip install pywal wal_steam` on any OS/Distro.

**Comment by kotajacob** [comment]
Wow that's really awesome and thanks for all the help. I've been working on windows support and I think I've just about got it so this is great.

I've been considering restructuring it into a pip package, but at the same time I really like it being one extremely simple script and of course lots of people have it "installed" via cloning the repo and it would force them to reinstall. So I think I'll play around more with shipping a windows binary. (Probably via a make file changing python to c then compiling that or maybe that py2exe thing, but I'm less familiar with that.)

(Also yea improving the readme and making a clear contributing guide is my next big goal)

**Comment by dylanaraps** [comment]
You can make `wal_steam` a `pip` package without making any changes to the script structure. You can keep it as a single file. All you need to do is add a `setup.py` that tells `pip` how to install it. I can send a PR once you merge `1.2.0` if you'd like.

**Comment by kotajacob** [comment]
Oh interesting, yea I'm pretty new to the whole python world. That seems really nice, I'll work on the rest of the stuff for 1.2.0 and then yea a pip package seems like a good idea. Also I'll check out using pywal as a module too that's a lot cleaner than my hacked together css parsing.

**Pull request merged**
