### PR TITLE
Fixed outdated URLs and set remote agent since one URL checks this

### PR DESCRIPTION
**Pull request by Zedjones**
Here ya go! I didn't want to make a PR because I wasn't sure if it was a problem everybody was experiencing, but if you tested it and it worked then it's probably good.

### CODE REVIEW

**Comment by Christopherbikie** [comment]
@Zedjones for whatever reason, I had to comment the try-except on lines 259 and 261-263 in `wal_steam.py`.

Since you were wondering if anyone else was experiencing issues: Previously I was experiencing the same issue as #58 but the updated patch seems to fix it.

**Comment by Zedjones** [comment]
@Christopherbikie Yeah, my issue was actually with downloading the files themselves. As in, the program would fail to download the files from the old URLs and unless I changed the User Agent. 

You had to comment out those lines in the version in this PR? That's odd.

**Comment by Zedjones** [comment]
@Christopherbikie Yeah, my issue was actually with downloading the files themselves. As in, the program would fail to download the files from the old URLs and unless I changed the User Agent. 

You had to comment out those lines in the version in this PR? That's odd.

**Comment by Zedjones** [comment]
@Christopherbikie Yeah, my issue was actually with downloading the files themselves. As in, the program would fail to download the files from the old URLs and unless I changed the User Agent. 

You had to comment out those lines in the version in this PR? That's odd.

**Comment by elock37** [comment]
This would fix #60 as well, though only for the 403 denials and not true connection issues. The checkSkin() function still assumes all downloads were handled successfully.

**Pull request merged**
